### PR TITLE
Proper implementation of ntcontrol protocol

### PR DESCRIPTION
**Pull request by peschuster**
This is basically a complete rewrite of the module with a proper implementation of the Panasonic ntcontrol protocol.

Changes:
- support of persistent connections to the projector
- variables and feedback
- presets
- actions for shutter fade in and fade out time
- actions to switch test patterns
- actions to set/change color matching

There are no upgrade functions for existing configurations, because the module is not yet part of companion builds (not included in main companion repository).

I tested the module for several months with multiple Panasonic projectors/models.

### CODE REVIEW

**Comment by krocheck** [comment]
@peschuster this is looking pretty good.  What testing have you completed?

**Comment by peschuster** [comment]
I systematically tested all actions, variables and feedback and also used it in some productions/events ranging from a few hours to several days.

**Comment by haakonnessjoen** [comment]
This module seems to rename/totally change a lot of actions, with no respect to old configurations. Or did I miss a totally visible upgrade script on my mobile screen? :p

**Comment by krocheck** [comment]
The module as originally written was never dropped into a build, so the changes wouldn't impact users.

**Comment by haakonnessjoen** [comment]
Great 👍🏻

**Pull request merged**
